#!/bin/bash


selected_dir=$(find ~/projects ~/ ~/work ~/tripleten -mindepth 1 -maxdepth 1 -type d | fzf)

# Check if a directory was selected
if [[ -n "$selected_dir" ]]; then

    # Open a new Kitty window in the selected directory (in the background)
    cd "$selected_dir" || return 
  else
    # Exit if no directory was selected
    echo "No directory selected. Exiting."
    exit 1
    fi

